/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;


import Class.SQLiteMethods;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class W_RegisterPrice extends javax.swing.JFrame {

    int heigh;
    String plantName;
    W_Menu wm;

    /**
     * Creates new form W_RegisterClient
     */
    public W_RegisterPrice(String plantName, int heigh,W_Menu w) {
        initComponents();
        this.setSize(450,211);
        setLocationRelativeTo(null);
        this.plantName = plantName;
        this.heigh = heigh;
        jLabelPlant.setText(this.plantName);
        jLabelheigh.setText(""+this.heigh);
        this.wm = w;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelheigh = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButtonClose1 = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelPlant = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButtonLogin3 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(467, 3));
        getContentPane().setLayout(null);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Altura:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(30, 90, 60, 40);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nuevo precio:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(30, 140, 100, 40);

        jLabelheigh.setBackground(new java.awt.Color(255, 255, 255));
        jLabelheigh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelheigh.setForeground(new java.awt.Color(255, 255, 255));
        jLabelheigh.setText("Nombre");
        getContentPane().add(jLabelheigh);
        jLabelheigh.setBounds(110, 90, 60, 40);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Planta:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(30, 50, 60, 40);

        jButtonClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose1.setBorder(null);
        jButtonClose1.setBorderPainted(false);
        jButtonClose1.setContentAreaFilled(false);
        jButtonClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose1.setRequestFocusEnabled(false);
        jButtonClose1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose1MouseClicked(evt);
            }
        });
        jButtonClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose1);
        jButtonClose1.setBounds(370, 10, 70, 60);

        jLabelTitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Registrar nuevo precio");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(20, 10, 320, 28);

        jLabelPlant.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPlant.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelPlant.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlant.setText("Nombre");
        getContentPane().add(jLabelPlant);
        jLabelPlant.setBounds(110, 50, 240, 40);

        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrice);
        jTextFieldPrice.setBounds(130, 150, 60, 24);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Registrar");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(310, 150, 80, 30);

        jButtonLogin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonLogin3.setBorder(null);
        jButtonLogin3.setBorderPainted(false);
        jButtonLogin3.setContentAreaFilled(false);
        jButtonLogin3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin3.setRequestFocusEnabled(false);
        jButtonLogin3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogin3MouseClicked(evt);
            }
        });
        jButtonLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin3);
        jButtonLogin3.setBounds(370, 130, 80, 70);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hydrogen.jpg"))); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(450, 300));
        bg.setMinimumSize(new java.awt.Dimension(450, 300));
        bg.setPreferredSize(new java.awt.Dimension(450, 300));
        getContentPane().add(bg);
        bg.setBounds(0, 0, 450, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jButtonLogin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogin3MouseClicked
        
    }//GEN-LAST:event_jButtonLogin3MouseClicked

    private void jButtonLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin3ActionPerformed
       try{
           double price = Double.parseDouble(jTextFieldPrice.getText());
           JOptionPane.showMessageDialog(rootPane, SQLiteMethods.getInstance().addPrice(this.plantName, this.heigh, price));
           wm.updatePrices();
           this.dispose();
       }
       catch(NumberFormatException  ex){
           JOptionPane.showMessageDialog(rootPane, "Digite un valor en formato: #.#");
       }
    }//GEN-LAST:event_jButtonLogin3ActionPerformed

    private void jButtonClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButtonClose1MouseClicked

    private void jButtonClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonClose1ActionPerformed


    public void loadRegisterClient(){
        jLabelTitle.setText("Registrar nuevo cliente");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonClose1;
    private javax.swing.JButton jButtonLogin3;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabelPlant;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelheigh;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
}
