/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Class.Methods;

/**
 *
 * @author Baxi
 */
public class W_Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form W_Main
     */
    public W_Menu() {
        initComponents();
        this.setSize(1200,800);
        setLocationRelativeTo(null);
        closePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonLogin1 = new javax.swing.JButton();
        jButtonLogin2 = new javax.swing.JButton();
        jButtonLogin3 = new javax.swing.JButton();
        jPanelBill = new javax.swing.JPanel();
        jButtonClose1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDatabase = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonRunQuery1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanelClients = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuery = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableQuery = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButtonRunQuery = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanelProducts = new javax.swing.JPanel();
        jButtonClose2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaQuery2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableQuery2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jButtonRunQuery2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanelAditionalData = new javax.swing.JPanel();
        jButtonClose3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaQuery3 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableQuery3 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jButtonRunQuery3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelMenu.setBackground(new java.awt.Color(5, 5, 5));
        jPanelMenu.setToolTipText("");
        jPanelMenu.setAlignmentX(0.0F);
        jPanelMenu.setAlignmentY(0.0F);
        jPanelMenu.setMaximumSize(new java.awt.Dimension(400, 800));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(400, 800));
        jPanelMenu.setName("panelLogin"); // NOI18N
        jPanelMenu.setPreferredSize(new java.awt.Dimension(400, 800));
        jPanelMenu.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 148, 148));
        jLabel3.setText("Menu");
        jLabel3.setToolTipText("");
        jPanelMenu.add(jLabel3);
        jLabel3.setBounds(140, 30, 89, 42);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Información de Factura");
        jPanelMenu.add(jLabel4);
        jLabel4.setBounds(50, 200, 250, 28);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Información de Cliente");
        jPanelMenu.add(jLabel5);
        jLabel5.setBounds(50, 300, 250, 28);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos Adicionales");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanelMenu.add(jLabel2);
        jLabel2.setBounds(50, 500, 210, 28);

        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonLogin.setBorder(null);
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setContentAreaFilled(false);
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.setRequestFocusEnabled(false);
        jButtonLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseClicked(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonLogin);
        jButtonLogin.setBounds(320, 490, 50, 50);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agregar Productos");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanelMenu.add(jLabel6);
        jLabel6.setBounds(50, 400, 210, 28);

        jButtonLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonLogin1.setBorder(null);
        jButtonLogin1.setBorderPainted(false);
        jButtonLogin1.setContentAreaFilled(false);
        jButtonLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin1.setRequestFocusEnabled(false);
        jButtonLogin1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogin1MouseClicked(evt);
            }
        });
        jButtonLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin1ActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonLogin1);
        jButtonLogin1.setBounds(320, 190, 50, 50);

        jButtonLogin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonLogin2.setBorder(null);
        jButtonLogin2.setBorderPainted(false);
        jButtonLogin2.setContentAreaFilled(false);
        jButtonLogin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin2.setRequestFocusEnabled(false);
        jButtonLogin2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogin2MouseClicked(evt);
            }
        });
        jButtonLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin2ActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonLogin2);
        jButtonLogin2.setBounds(320, 290, 50, 50);

        jButtonLogin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonLogin3.setBorder(null);
        jButtonLogin3.setBorderPainted(false);
        jButtonLogin3.setContentAreaFilled(false);
        jButtonLogin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin3.setRequestFocusEnabled(false);
        jButtonLogin3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogin3MouseClicked(evt);
            }
        });
        jButtonLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin3ActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonLogin3);
        jButtonLogin3.setBounds(320, 390, 50, 50);

        getContentPane().add(jPanelMenu);
        jPanelMenu.setBounds(0, 0, 400, 800);

        jPanelBill.setBackground(new java.awt.Color(102, 102, 102));
        jPanelBill.setAlignmentX(0.0F);
        jPanelBill.setAlignmentY(0.0F);
        jPanelBill.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanelBill.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanelBill.setLayout(null);

        jButtonClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose1.setBorder(null);
        jButtonClose1.setBorderPainted(false);
        jButtonClose1.setContentAreaFilled(false);
        jButtonClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose1.setRequestFocusEnabled(false);
        jButtonClose1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose1MouseClicked(evt);
            }
        });
        jButtonClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose1ActionPerformed(evt);
            }
        });
        jPanelBill.add(jButtonClose1);
        jButtonClose1.setBounds(710, 40, 50, 50);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Seleccione la Fecha ");
        jPanelBill.add(jLabel11);
        jLabel11.setBounds(130, 310, 210, 28);

        jTextFieldDatabase.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldDatabase.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldDatabase.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDatabase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanelBill.add(jTextFieldDatabase);
        jTextFieldDatabase.setBounds(380, 160, 290, 40);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Número de Factura");
        jPanelBill.add(jLabel19);
        jLabel19.setBounds(130, 160, 220, 28);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Siguiente");
        jPanelBill.add(jLabel12);
        jLabel12.setBounds(250, 620, 110, 28);

        jButtonRunQuery1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonRunQuery1.setBorder(null);
        jButtonRunQuery1.setBorderPainted(false);
        jButtonRunQuery1.setContentAreaFilled(false);
        jButtonRunQuery1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRunQuery1.setRequestFocusEnabled(false);
        jButtonRunQuery1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRunQuery1MouseClicked(evt);
            }
        });
        jButtonRunQuery1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunQuery1ActionPerformed(evt);
            }
        });
        jPanelBill.add(jButtonRunQuery1);
        jButtonRunQuery1.setBounds(390, 610, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoPanel.png"))); // NOI18N
        jLabel8.setAlignmentY(0.0F);
        jLabel8.setMaximumSize(new java.awt.Dimension(800, 800));
        jLabel8.setMinimumSize(new java.awt.Dimension(800, 800));
        jLabel8.setName(""); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanelBill.add(jLabel8);
        jLabel8.setBounds(0, 0, 800, 800);

        getContentPane().add(jPanelBill);
        jPanelBill.setBounds(400, 0, 800, 800);

        jPanelClients.setBackground(new java.awt.Color(102, 102, 102));
        jPanelClients.setAlignmentX(0.0F);
        jPanelClients.setAlignmentY(0.0F);
        jPanelClients.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanelClients.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanelClients.setLayout(null);

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose.setBorder(null);
        jButtonClose.setBorderPainted(false);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose.setRequestFocusEnabled(false);
        jButtonClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanelClients.add(jButtonClose);
        jButtonClose.setBounds(710, 40, 50, 50);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Clientes");
        jPanelClients.add(jLabel9);
        jLabel9.setBounds(240, 50, 280, 28);

        jTextAreaQuery.setBackground(new java.awt.Color(5, 5, 5));
        jTextAreaQuery.setColumns(20);
        jTextAreaQuery.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextAreaQuery.setForeground(new java.awt.Color(0, 204, 204));
        jTextAreaQuery.setRows(5);
        jTextAreaQuery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        jTextAreaQuery.setSelectionColor(new java.awt.Color(51, 153, 0));
        jScrollPane1.setViewportView(jTextAreaQuery);

        jPanelClients.add(jScrollPane1);
        jScrollPane1.setBounds(50, 100, 710, 190);

        jScrollPane2.setBackground(new java.awt.Color(5, 5, 5));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(600, 600));

        jTableQuery.setBackground(new java.awt.Color(5, 5, 5));
        jTableQuery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jTableQuery.setForeground(new java.awt.Color(51, 255, 255));
        jTableQuery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTableQuery.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTableQuery.setMinimumSize(new java.awt.Dimension(1, 100));
        jTableQuery.setName(""); // NOI18N
        jTableQuery.setPreferredSize(new java.awt.Dimension(20, 100000));
        jTableQuery.setSelectionBackground(new java.awt.Color(51, 153, 0));
        jScrollPane2.setViewportView(jTableQuery);

        jPanelClients.add(jScrollPane2);
        jScrollPane2.setBounds(50, 300, 710, 420);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Execute");
        jPanelClients.add(jLabel10);
        jLabel10.setBounds(320, 740, 110, 28);

        jButtonRunQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonRunQuery.setBorder(null);
        jButtonRunQuery.setBorderPainted(false);
        jButtonRunQuery.setContentAreaFilled(false);
        jButtonRunQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRunQuery.setRequestFocusEnabled(false);
        jButtonRunQuery.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRunQueryMouseClicked(evt);
            }
        });
        jButtonRunQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunQueryActionPerformed(evt);
            }
        });
        jPanelClients.add(jButtonRunQuery);
        jButtonRunQuery.setBounds(450, 730, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoPanel.png"))); // NOI18N
        jLabel7.setAlignmentY(0.0F);
        jLabel7.setMaximumSize(new java.awt.Dimension(800, 800));
        jLabel7.setMinimumSize(new java.awt.Dimension(800, 800));
        jLabel7.setName(""); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanelClients.add(jLabel7);
        jLabel7.setBounds(0, 0, 800, 800);

        getContentPane().add(jPanelClients);
        jPanelClients.setBounds(400, 0, 800, 800);

        jPanelProducts.setBackground(new java.awt.Color(102, 102, 102));
        jPanelProducts.setAlignmentX(0.0F);
        jPanelProducts.setAlignmentY(0.0F);
        jPanelProducts.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanelProducts.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanelProducts.setLayout(null);

        jButtonClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose2.setBorder(null);
        jButtonClose2.setBorderPainted(false);
        jButtonClose2.setContentAreaFilled(false);
        jButtonClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose2.setRequestFocusEnabled(false);
        jButtonClose2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose2MouseClicked(evt);
            }
        });
        jButtonClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose2ActionPerformed(evt);
            }
        });
        jPanelProducts.add(jButtonClose2);
        jButtonClose2.setBounds(710, 40, 50, 50);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Productos");
        jPanelProducts.add(jLabel13);
        jLabel13.setBounds(240, 50, 280, 28);

        jTextAreaQuery2.setBackground(new java.awt.Color(5, 5, 5));
        jTextAreaQuery2.setColumns(20);
        jTextAreaQuery2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextAreaQuery2.setForeground(new java.awt.Color(0, 204, 204));
        jTextAreaQuery2.setRows(5);
        jTextAreaQuery2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        jTextAreaQuery2.setSelectionColor(new java.awt.Color(51, 153, 0));
        jScrollPane5.setViewportView(jTextAreaQuery2);

        jPanelProducts.add(jScrollPane5);
        jScrollPane5.setBounds(50, 100, 710, 190);

        jScrollPane6.setBackground(new java.awt.Color(5, 5, 5));
        jScrollPane6.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(600, 600));

        jTableQuery2.setBackground(new java.awt.Color(5, 5, 5));
        jTableQuery2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jTableQuery2.setForeground(new java.awt.Color(51, 255, 255));
        jTableQuery2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTableQuery2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTableQuery2.setMinimumSize(new java.awt.Dimension(1, 100));
        jTableQuery2.setName(""); // NOI18N
        jTableQuery2.setPreferredSize(new java.awt.Dimension(20, 100000));
        jTableQuery2.setSelectionBackground(new java.awt.Color(51, 153, 0));
        jScrollPane6.setViewportView(jTableQuery2);

        jPanelProducts.add(jScrollPane6);
        jScrollPane6.setBounds(50, 300, 710, 420);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Execute");
        jPanelProducts.add(jLabel14);
        jLabel14.setBounds(320, 740, 110, 28);

        jButtonRunQuery2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonRunQuery2.setBorder(null);
        jButtonRunQuery2.setBorderPainted(false);
        jButtonRunQuery2.setContentAreaFilled(false);
        jButtonRunQuery2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRunQuery2.setRequestFocusEnabled(false);
        jButtonRunQuery2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRunQuery2MouseClicked(evt);
            }
        });
        jButtonRunQuery2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunQuery2ActionPerformed(evt);
            }
        });
        jPanelProducts.add(jButtonRunQuery2);
        jButtonRunQuery2.setBounds(450, 730, 50, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoPanel.png"))); // NOI18N
        jLabel15.setAlignmentY(0.0F);
        jLabel15.setMaximumSize(new java.awt.Dimension(800, 800));
        jLabel15.setMinimumSize(new java.awt.Dimension(800, 800));
        jLabel15.setName(""); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanelProducts.add(jLabel15);
        jLabel15.setBounds(0, 0, 800, 800);

        getContentPane().add(jPanelProducts);
        jPanelProducts.setBounds(400, 0, 800, 800);

        jPanelAditionalData.setBackground(new java.awt.Color(102, 102, 102));
        jPanelAditionalData.setAlignmentX(0.0F);
        jPanelAditionalData.setAlignmentY(0.0F);
        jPanelAditionalData.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanelAditionalData.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanelAditionalData.setLayout(null);

        jButtonClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose3.setBorder(null);
        jButtonClose3.setBorderPainted(false);
        jButtonClose3.setContentAreaFilled(false);
        jButtonClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose3.setRequestFocusEnabled(false);
        jButtonClose3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose3MouseClicked(evt);
            }
        });
        jButtonClose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose3ActionPerformed(evt);
            }
        });
        jPanelAditionalData.add(jButtonClose3);
        jButtonClose3.setBounds(710, 40, 50, 50);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Datos Adicionales");
        jPanelAditionalData.add(jLabel16);
        jLabel16.setBounds(240, 50, 280, 28);

        jTextAreaQuery3.setBackground(new java.awt.Color(5, 5, 5));
        jTextAreaQuery3.setColumns(20);
        jTextAreaQuery3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextAreaQuery3.setForeground(new java.awt.Color(0, 204, 204));
        jTextAreaQuery3.setRows(5);
        jTextAreaQuery3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        jTextAreaQuery3.setSelectionColor(new java.awt.Color(51, 153, 0));
        jScrollPane7.setViewportView(jTextAreaQuery3);

        jPanelAditionalData.add(jScrollPane7);
        jScrollPane7.setBounds(50, 100, 710, 190);

        jScrollPane8.setBackground(new java.awt.Color(5, 5, 5));
        jScrollPane8.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane8.setPreferredSize(new java.awt.Dimension(600, 600));

        jTableQuery3.setBackground(new java.awt.Color(5, 5, 5));
        jTableQuery3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jTableQuery3.setForeground(new java.awt.Color(51, 255, 255));
        jTableQuery3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTableQuery3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTableQuery3.setMinimumSize(new java.awt.Dimension(1, 100));
        jTableQuery3.setName(""); // NOI18N
        jTableQuery3.setPreferredSize(new java.awt.Dimension(20, 100000));
        jTableQuery3.setSelectionBackground(new java.awt.Color(51, 153, 0));
        jScrollPane8.setViewportView(jTableQuery3);

        jPanelAditionalData.add(jScrollPane8);
        jScrollPane8.setBounds(50, 300, 710, 420);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Execute");
        jPanelAditionalData.add(jLabel17);
        jLabel17.setBounds(320, 740, 110, 28);

        jButtonRunQuery3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonRunQuery3.setBorder(null);
        jButtonRunQuery3.setBorderPainted(false);
        jButtonRunQuery3.setContentAreaFilled(false);
        jButtonRunQuery3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRunQuery3.setRequestFocusEnabled(false);
        jButtonRunQuery3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonRunQuery3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRunQuery3MouseClicked(evt);
            }
        });
        jButtonRunQuery3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunQuery3ActionPerformed(evt);
            }
        });
        jPanelAditionalData.add(jButtonRunQuery3);
        jButtonRunQuery3.setBounds(450, 730, 50, 50);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoPanel.png"))); // NOI18N
        jLabel18.setAlignmentY(0.0F);
        jLabel18.setMaximumSize(new java.awt.Dimension(800, 800));
        jLabel18.setMinimumSize(new java.awt.Dimension(800, 800));
        jLabel18.setName(""); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanelAditionalData.add(jLabel18);
        jLabel18.setBounds(0, 0, 800, 800);

        getContentPane().add(jPanelAditionalData);
        jPanelAditionalData.setBounds(400, 0, 800, 800);

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jButtonLogout.setBorder(null);
        jButtonLogout.setBorderPainted(false);
        jButtonLogout.setContentAreaFilled(false);
        jButtonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogout.setRequestFocusEnabled(false);
        jButtonLogout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout2.png"))); // NOI18N
        jButtonLogout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout2.png"))); // NOI18N
        jButtonLogout.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout2.png"))); // NOI18N
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseClicked(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogout);
        jButtonLogout.setBounds(1120, 40, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backg.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseClicked
        W_Login w = new W_Login();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutMouseClicked

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
   
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseClicked
        closePanels();
        changeSize(jPanelAditionalData);
    }//GEN-LAST:event_jButtonLoginMouseClicked

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButtonLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogin1MouseClicked
        closePanels();
        changeSize(jPanelBill);
        
    }//GEN-LAST:event_jButtonLogin1MouseClicked

    private void jButtonLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogin1ActionPerformed

    private void jButtonLogin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogin2MouseClicked
        closePanels();
        changeSize(jPanelClients);
    }//GEN-LAST:event_jButtonLogin2MouseClicked

    private void jButtonLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogin2ActionPerformed

    private void jButtonLogin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogin3MouseClicked
        closePanels();
        changeSize(jPanelProducts);
    }//GEN-LAST:event_jButtonLogin3MouseClicked

    private void jButtonLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogin3ActionPerformed

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        closePanels();
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonRunQueryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRunQueryMouseClicked
        

    }//GEN-LAST:event_jButtonRunQueryMouseClicked
    public void changeSize(javax.swing.JPanel panel){
        panel.setVisible(true);
       
    }
    
    public void closePanels(){
        jPanelBill.setVisible(false);
        jPanelClients.setVisible(false);
        jPanelProducts.setVisible(false);
        jPanelAditionalData.setVisible(false);
    }
    private void jButtonRunQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunQueryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRunQueryActionPerformed

    private void jButtonClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose1MouseClicked
        closePanels();
    }//GEN-LAST:event_jButtonClose1MouseClicked

    private void jButtonClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose1ActionPerformed

    private void jButtonRunQuery1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRunQuery1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRunQuery1MouseClicked

    private void jButtonRunQuery1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunQuery1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRunQuery1ActionPerformed

    private void jButtonClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose2MouseClicked
        closePanels();
    }//GEN-LAST:event_jButtonClose2MouseClicked

    private void jButtonClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose2ActionPerformed

    private void jButtonRunQuery2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRunQuery2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRunQuery2MouseClicked

    private void jButtonRunQuery2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunQuery2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRunQuery2ActionPerformed

    private void jButtonClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose3MouseClicked
        closePanels();
    }//GEN-LAST:event_jButtonClose3MouseClicked

    private void jButtonClose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose3ActionPerformed

    private void jButtonRunQuery3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRunQuery3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRunQuery3MouseClicked

    private void jButtonRunQuery3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunQuery3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRunQuery3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(W_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(W_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(W_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(W_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new W_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonClose1;
    private javax.swing.JButton jButtonClose2;
    private javax.swing.JButton jButtonClose3;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogin1;
    private javax.swing.JButton jButtonLogin2;
    private javax.swing.JButton jButtonLogin3;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRunQuery;
    private javax.swing.JButton jButtonRunQuery1;
    private javax.swing.JButton jButtonRunQuery2;
    private javax.swing.JButton jButtonRunQuery3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAditionalData;
    private javax.swing.JPanel jPanelBill;
    private javax.swing.JPanel jPanelClients;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelProducts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTableQuery;
    private javax.swing.JTable jTableQuery2;
    private javax.swing.JTable jTableQuery3;
    private javax.swing.JTextArea jTextAreaQuery;
    private javax.swing.JTextArea jTextAreaQuery2;
    private javax.swing.JTextArea jTextAreaQuery3;
    private javax.swing.JTextField jTextFieldDatabase;
    // End of variables declaration//GEN-END:variables
}
