/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Class.SQLLiteMethods;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class W_RegisterClient extends javax.swing.JFrame {
    int clientId;
    int format;

    /**
     * Creates new form W_RegisterClient
     */
    public W_RegisterClient(int format) {
        initComponents();
        this.setSize(446,298);
        setLocationRelativeTo(null);
        this.format = format;
        if(format==1){
            loadRegisterClient();
        }
        else{
            loadRegisterNotify();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelExport = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldExport = new javax.swing.JTextField();
        jTextFieldDirection = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTelephone = new javax.swing.JTextField();
        jButtonLogin3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonClose1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListClients = new javax.swing.JList<>();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(467, 3));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 60, 20);

        jLabelExport.setText("Exporte:");
        getContentPane().add(jLabelExport);
        jLabelExport.setBounds(30, 220, 60, 20);

        jLabel3.setText("Dirección:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 70, 20);

        jLabel4.setText("Teléfono:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 60, 20);

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(110, 60, 260, 24);

        jLabelTitle.setText("Registrar nuevo cliente");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(170, 10, 140, 25);

        jTextFieldExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExportActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldExport);
        jTextFieldExport.setBounds(110, 220, 260, 24);

        jTextFieldDirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirectionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDirection);
        jTextFieldDirection.setBounds(110, 100, 260, 24);

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(110, 180, 260, 24);

        jLabel6.setText("Email:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 180, 50, 20);

        jTextFieldTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelephoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelephone);
        jTextFieldTelephone.setBounds(110, 140, 260, 24);

        jButtonLogin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonLogin3.setBorder(null);
        jButtonLogin3.setBorderPainted(false);
        jButtonLogin3.setContentAreaFilled(false);
        jButtonLogin3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin3.setRequestFocusEnabled(false);
        jButtonLogin3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonLogin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogin3MouseClicked(evt);
            }
        });
        jButtonLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin3);
        jButtonLogin3.setBounds(380, 240, 80, 60);

        jLabel7.setText("Registrar");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 250, 60, 40);

        jButtonClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose1.setBorder(null);
        jButtonClose1.setBorderPainted(false);
        jButtonClose1.setContentAreaFilled(false);
        jButtonClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose1.setRequestFocusEnabled(false);
        jButtonClose1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose1MouseClicked(evt);
            }
        });
        jButtonClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose1);
        jButtonClose1.setBounds(390, 10, 60, 50);

        jListClients.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListClients.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListClientsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListClients);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 220, 260, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExportActionPerformed

    private void jTextFieldDirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDirectionActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelephoneActionPerformed

    private void jButtonLogin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogin3MouseClicked
        
    }//GEN-LAST:event_jButtonLogin3MouseClicked

    private void jButtonLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin3ActionPerformed
        // TODO add your handling code here:
        if(format == 1){
            String name = jTextFieldName.getText();
            String export = jTextFieldExport.getText();
            String direction = jTextFieldDirection.getText();
            String phone = jTextFieldTelephone.getText();
            String email = jTextFieldEmail.getText(); // Falta por hacer
            JOptionPane.showMessageDialog(rootPane, SQLLiteMethods.getInstance().addClient(name, export, direction, phone)); 
            jTextFieldName.setText("");
            jTextFieldExport.setText("");
            jTextFieldDirection.setText("");
            jTextFieldTelephone.setText("");
            jTextFieldEmail.setText("");
        }
        else{
            String name = jTextFieldName.getText();
            String direction = jTextFieldDirection.getText();
            String phone = jTextFieldTelephone.getText();
            String email = jTextFieldEmail.getText();
            JOptionPane.showMessageDialog(rootPane, SQLLiteMethods.getInstance().addNotifyTo(name, direction, phone, email, clientId)); 
            jTextFieldName.setText("");
            jTextFieldExport.setText("");
            jTextFieldDirection.setText("");
            jTextFieldTelephone.setText("");
            jTextFieldEmail.setText("");
        } 
    }//GEN-LAST:event_jButtonLogin3ActionPerformed

    private void jButtonClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButtonClose1MouseClicked

    private void jButtonClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose1ActionPerformed

    private void jListClientsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListClientsValueChanged
        // TODO add your handling code here:
         String client = jListClients.getSelectedValue();
         String[] dataClient = client.split("\\) ");
         this.clientId = Integer.parseInt(dataClient[0]);
    }//GEN-LAST:event_jListClientsValueChanged


    public void loadRegisterNotify(){
        jTextFieldExport.setVisible(false);
        jListClients.setVisible(true);
        jLabelExport.setText("Cliente:");
        jLabelTitle.setText("Registrar nuevo notificado");
        jListClients.setModel(SQLLiteMethods.getInstance().getClientList());
    }
    
    public void loadRegisterClient(){
        jListClients.setVisible(false);
        jTextFieldExport.setVisible(true);
        jLabelExport.setText("Exporte:");
        jLabelTitle.setText("Registrar nuevo cliente");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonClose1;
    private javax.swing.JButton jButtonLogin3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelExport;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jListClients;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDirection;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldExport;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
